# Generated by Django 3.2.9 on 2023-09-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='upvideo/')),
                ('email', models.EmailField(max_length=128, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='upimage',
            name='image',
            field=models.ImageField(upload_to='upimg/'),
        ),
    ]
