# Generated by Django 3.2.9 on 2023-09-21 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upimage',
            old_name='image_file',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='upvideo',
            old_name='video_file',
            new_name='video',
        ),
    ]
